# Generated by Django 6.0.6 on 2026-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of large bags'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_km',
            field=models.PositiveIntegerField(default=0, help_text='Total km on the odometer'),
        ),
    ]
