# Generated by Django 6.0.6 on 2026-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_car_doors_car_fuel_type_car_luggage_car_mileage_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
