# Generated by Django 6.0.6 on 2026-06-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_car_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='total_price',
        ),
    ]
