# Generated by Django 6.0.6 on 2026-06-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_car_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='luggage',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='Number of large bags'),
        ),
    ]
