# Generated by Django 6.0.6 on 2026-06-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_copy_photo_to_carphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
    ]
